LUAFDN-755: Strongly type the primary public APIs of React (#267)
* Align all hooks function generics to upstream. 

* Make hooks tests pass strict. finding some good type bugs present in upstream!

* Fix more type issues. This commit captures a bug in Luau output where it gives the wrong line number, which should be 15: TypeError: Redefinition of type 'React_Node', previously defined at line 1. This was reported as CLI-49044 and the fix is now merged

* Thread forwardref types through. I'm sure I missed a hop somewhere, and we'll need to test it by making forwardRef tests strict.

* Attempt to tighten up memo. Upstream types don't make sense, and IntelliJ/DefinitelyTyped have incompatibilities when you do memo(forwardRef(..)). ugh.

* Capture a situation where Luau isn't inferring A correctly, even when the reducer is inline, with a comment showing what I have to do manually to appease it. It seems to me that the missing argument on the concrete function should mean it infers A to be nil, just like the manual annotation does.

* Extract flowtypes to their own file.

* Export types from React module like definitelytyped does and apollo-client depends on.

* This is why we integration test. A very subtle type annotation difference (that Luau should warn about) for the case where the useEffect create function parameter returns a destructor function. Found by testing integration with apollo-client and going through the luau analyze errors.

* Use new Luau singleton type feature, which better matches upstream.

* It looks like the flowtype annotations don't accurately model ref.current. It doesn't model the 'empty' initial value (if passed nil), and doesn't allow one to clear the current value in a way that cleanly typechecks.

* Experiment to strongly type WorkLoop, which found a real bug (commented). Many Luau FIXME comments, all filed as CLI tickets. Will remove strict mode on that file, which isn't part of the public API surface anyway, for now.

* Fix a type mismatch between our Ordered Set and the lightweight 'simple' Set. The interactions need to be an ordered Set to make tests pass, so this change allows both kinds to co-exist. Very cool that type checking catches this now even in non-strict!

* Making some files strict so Luau analyze can get further on some test files in strict mode. Fixes one potential nil deref bug even though it would only occur in tests.

* A leap forward by doing a deep workaround for Luau type pack issues. Commiting here to capture a bizzare false positive from Luau: ReactBaseClasses.lua:55:3-13: (E001) TypeError: Expected to return 2 values, but 1 is returned here

* Using Array.concat properly now retains types and silences an analyze warning

* Use the public ReactElement<>. This highlights a general issue -- when to use ReactElement vs React_Element, or React_Node vs ReactNode, and can Luau see them as compatible types (assuming they are compatible)?

* ugh. forwardRef.spec.lua:326:65-95: (E001) TypeError: Type '{ optional: string, ref: any }' could not be converted into 'any?'; none of the union options are compatible

* Fix some more irrational upstream code. enabling strict mode for Memo is blocked by normalization landing in Luau (at least).

* Strongly type react-is and align so that other test files typecheck cleanly.

* ReactFiber now strict. RoactStableKey may not be modeling things correctly enough, but numbers may be coerced into strings anyway?

* A few more strict files. Found a small deviation to fix. () -> mixed should translate to () -> ...any

* A few more minor fixes for fallout. Even in non-strict, more analysis is happening and finding real type misalignments, which is cool!

* Adjust content of ReactTypes to align, have cleaner separation between customizations. Adjust top-level React type exports to do the same.

* The metatable warnings look like real bugs to me, but let's fix those in a separate PR.

* Capture the SchedulerWithReactIntegration.new.lua:160:3-53: (E001) TypeError: Failed to unify variadic packs

* add validateProps field. Remove some Luau workarounds that aren't needed anymore. Update some workaround comments. Unskip some tests.

* add self parameter to lifecycle methods. this had some ripple effects that highlighted that memo() signature was slightly incorrect.

* Fix some tests that were broken by attempts to please the type checker; instead, mark them as nonstrict for now

* Fix element._store metatable tomfoolery to work as intended

* Align double-key warning logic to intent, add more info to the warning

* Went through with React.lua in strict mode and fixed up several things that highlights. Really cool to see type analysis finding so many things in the tests!

* Fix subtype escape error. A legit type bug in our Lua, but the error message was obtuse. Warning message improvement filed as https://jira.rbx.com/browse/CLI-51166

* fix the useMutableSource bug. fix the type issue by doing a better translation of upstream type cast, which I apparently saw and filed in js-to-lua here: https://github.com/Roblox/js-to-lua/issues/383

* Allow for string-indexed tables of React_Node, but at a cost -- now React_Element field types will no longer resolve.

* Fix the Promise type. It turns out we need to force cast the key to string, otherwise Luau can't resolve for some reason.